<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'RG\\TtNews\\' => array($typo3InstallDir . 'typo3conf/ext/tt_news/Classes'),
    'WapplerSystems\\WsFlexslider\\' => array($typo3InstallDir . 'typo3conf/ext/ws_flexslider/Classes'),
);
